hydra:
  run:
    dir: .
  hydra_logging: null
  #output_subdir: null
  job_logging: null


data:
  train:
    dataloader:
      _target_: src.datasets.LLFFDataloader
      data_dir: "../../mip-nerf-datasets/llff/orchids/"
      split: "train"
      near: 0.
      far: 1.
      factor: 4
      llffhold: 8
      batching_mode: "all_images"
      to_render_path: false
      to_spherify: false
      drop_last: false
      shuffle: true
      num_workers: 1

training:
  weight_decay_mult: 0.
  optimizer:
    _target_: torch.optim.Adam
  disable_multiscale_loss: false
  total_step: 1000000
  coarse_loss_mult: 0.1
  grad_max_val: 0.
  grad_max_norm: 0.
  randomized: true
  white_bg: false